### PR TITLE
Milestone 2: User interface

### PR DESCRIPTION
**Pull request by rida-elbahtouri**
### Milestone 2: User interface

**In this project we:**

1. created the basic logic

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi Team 👋

You've done quite ok on this. 👌

However, let's make the following adjustments:

- [ ]  You are required to run a loop that is expected to break if a certain condition is met. In the loop you are to do the following:

- Tell which player's turn it is.
- Display the board before each move
- Tell the player to choose from available moves.
- Inform the player if the move is a winning move.

In addition, note that it is ok to use inline comments in this milestone.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

🚀🚀HAPPY CODING🚀🚀

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work implementing the suggested changes :clap: However, further changes need to be applied in order to get approval for this milestone. Check :arrow_down: 

##### Implementation details

* [ ] Inside the loop, each iteration deals with actions for one player only (e.g DRY rules should be respected)
* [ ] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

```ruby
game_on = true

# initial instructions for player
current_player = player_one
while game_on
  # Same actions as you listed in your loop but for a single player
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  else
   # switch current_player
  end
end
```

* [ ] Using out-of-nowhere numbers to terminate a loop, for example, `5.times do ... end` is a signal that something is wrong. Usage of terminating variable as above is required.

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great progress @team :clap: :clap: However, further changes need to be applied in order to get approval for this milestone. Check :arrow_down: 

- **[REQUIRED]** You didn't implement the **switching** turn mechanism, you code as it is won't switch between the two players at the end of every iteration. :pray: refer to the suggestion that I gave in my previous review (_current_player_ is the player that enters the loop, interact with every action, gets switched at the end of loop if the game is not finished)

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by Dandush03** [comment]
# Status: 🟢 Approved 🟢 

Great job implementing requested changes

##### Good luck in your next milestone

### Happy Coding

**Pull request merged**
